# Generated by Django 5.1.4 on 2024-12-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['manufacturer', 'model']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
